### ISSUE TITLE
feature req : add an option to invert Q/A (AZERTY board)

### ISSUE THREAD

**Issue by bizulk** [BdR76/lcdgame.js#2]
Hello !

Thanks for the games.
I tried the mario bros one, be it would be easier if I could invert Q/A because I'm on azery board and these touch are inverted compared to the qwerty board.
Thank

**Comment by BdR76** [comment]
Thanks for the feedback. In a [recent update](https://github.com/BdR76/lcdgame.js/commit/bd55c6c5abe906d06fe92b8cb3b080d707beb70c) I've added alternative keyboard keys to all games, for example Highway can be controlled with either the cursor keys or the A/D keys. This is not mentioned in the help-dialogs, in part because there is not enough room in this text dialog.

Anyway, for Mario Bros the alternative keys are:  
* Luigi (left side) up/down with keys Q/A or I/K or Home/End
* Mario (right side) up/down with keys P/L or E/D or PgUp/PgDn

On an Azerty-keyboard the combination I/K and P/L should be playable, or else HOME/END and PGUP/PGDN. Hope that helps,
Bas
